# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Color-Calc
version:      0.29_0003
version_from: Calc.pm
installdirs:  site
requires:
    Graphics::ColorNames:          0.32
    Graphics::ColorNames::SVG:     0
    Params::Validate:              0.75

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
